version: 2
updates:
- package-ecosystem: bundler
  directory: "/integration"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - chrispymm
  - H3ll3m4
  - StevenLeighton21
- package-ecosystem: docker
  directory: "/integration"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - mattempty
  - chrispymm
  - H3ll3m4
  - StevenLeighton21
