version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  # Disable version updates, but leave security updates
  open-pull-requests-limit: 0

- package-ecosystem: bundler
  directory: "/integration"
  schedule:
    interval: daily
  # Disable version updates, but leave security updates
  open-pull-requests-limit: 0

- package-ecosystem: docker
  directory: "/integration"
  schedule:
    interval: daily
  # Disable version updates, but leave security updates
  open-pull-requests-limit: 0
