version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Prepare the repository
          command: bundle install
      - run:
          name: Setup the platform
          command: make platform
      - run:
          name: Setup the forms
          command: make services
      - run:
          name: Start all containers
          command: make start
      - run:
          name: Run acceptance tests
          command: make spec

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
