version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Setup chrome webdriver
          command: |
            sudo apt-get update
            sudo curl -sS https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - && sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
            sudo apt-get update && apt-get install google-chrome-stable=73.0.3683.86-1
            sudo wget https://chromedriver.storage.googleapis.com/73.0.3683.68/chromedriver_linux64.zip && sudo unzip chromedriver_linux64.zip -d /usr/local/bin && sudo rm chromedriver_linux64.zip
      - run:
          name: Setup the repository
          command: bundle install
      - run:
          name: Run tests
          command: ./bin/acceptance-tests --setup --run

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
