version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Prepare the repository
          command: bundle install
      - run:
          name: Setup the repository
          command: make setup

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
