version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: run tests
          command: ./bin/acceptance-tests --setup

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
