version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:3.2.2
    resource_class: large
    parameters:
      spec_dir:
        description: Directory where to look for specs to run
        type: string
        default: spec
    steps:
      - setup_remote_docker
      - checkout
      - restore_cache:
          keys:
            - &gem-cache gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1
      - run:
          name: Install gem dependencies
          command: bundle config set --local path 'vendor/bundle' && bundle install --jobs 4 --retry 3
      - save_cache:
          key: *gem-cache
          paths:
            - vendor/bundle
      - run:
          name: Setup the tests
          command: make setup-ci -s # -s hides output of environment variables in logs
      - run:
          name: Run acceptance tests
          command: make spec-ci SPEC_DIR=<< parameters.spec_dir >>
  clear_old_emails:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Prepare the repository
          command: BUNDLE_GEMFILE=./integration/Gemfile bundle install
      - run:
          name: Clear old emails
          command: make clear-emails

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test:
          context: &context
            - moj-forms
          matrix:
            parameters:
              spec_dir: ["spec/features/v2"] # "spec/lib", "spec/components", "spec/features/v1",

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - clear_old_emails:
          context: *context
