version: 2.1

jobs:
  test:
    docker:
      - image: cimg/ruby:2.7.2
    resource_class: large
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Prepare the repository
          command: bundle install
      - run:
          name: Setup the tests
          command: make setup-ci -s # -s hides output of environment variables in logs
      - run:
          name: Run acceptance tests
          command: make spec-ci
  clear_old_emails:
    docker:
      - image: cimg/ruby:2.7.2
    steps:
      - checkout
      - run:
          name: Prepare the repository
          command: BUNDLE_GEMFILE=./integration/Gemfile bundle install
      - run:
          name: Clear old emails
          command: make clear-emails

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - clear_old_emails
