version: 2.1

jobs:
  test:
    docker:
      - image: circleci/ruby:latest
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Prepare the repository
          command: bundle install
     #- run:
     #name: Setup the tests
     #command: make setup-ci -s # -s hides output of environment variables in logs
      - run:
          name: Setup the tests
          command: make setup
      - run:
          name: Run acceptance tests
          command: make spec

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
