source 'http://rubygems.org'

gem 'activesupport'
gem 'byebug'
gem 'capybara'
gem 'dotenv'
gem 'google-api-client'
gem 'httparty'
gem 'jwe'
gem 'mail'
gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false
gem 'parallel_tests'
gem 'pdf-reader'
gem 'rspec'
gem 'selenium-webdriver'
gem 'site_prism'
